create sequence renovation_user_seq start with 1 increment by 50 nocache;
create table authority (authority_id bigint not null auto_increment, user_id bigint, role varchar(255), primary key (authority_id)) engine=InnoDB;
create table forgotten_password_token (expiry_date datetime(6) not null, user_id bigint not null, id binary(16) not null, primary key (id)) engine=InnoDB;
create table renovation (is_public bit, created_timestamp datetime(6), id bigint not null auto_increment, user_id bigint not null, description varchar(600) not null, city varchar(255), country varchar(255), name varchar(255) not null, postcode varchar(255), region varchar(255), street_address varchar(255), suburb varchar(255), primary key (id)) engine=InnoDB;
create table renovation_user (activated bit, created_timestamp datetime(6), id bigint not null, city varchar(255), country varchar(255), email varchar(255) not null, fname varchar(255) not null, image varchar(255), lname varchar(255) not null, password varchar(255) not null, postcode varchar(255), region varchar(255), street_address varchar(255), suburb varchar(255), primary key (id)) engine=InnoDB;
create table room (id bigint not null auto_increment, renovation_id bigint not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table tag (renovation bigint not null, tag varchar(255) not null, primary key (renovation, tag)) engine=InnoDB;
create table task (due_date date, id bigint not null auto_increment, renovation_id bigint not null, description varchar(600) not null, icon_file_name varchar(255) not null, name varchar(255) not null, state enum ('NOT_STARTED','IN_PROGRESS','BLOCKED','COMPLETED','CANCELLED') not null, primary key (id)) engine=InnoDB;
create table task_room (room_id bigint not null, task_id bigint not null) engine=InnoDB;
create table verification_token (expiry_date datetime(6) not null, id bigint not null auto_increment, user_id bigint not null, token varchar(255) not null, primary key (id)) engine=InnoDB;
alter table forgotten_password_token add constraint UK_qnr9y2kxklc1ovc7tmf8mq2rs unique (user_id);
alter table verification_token add constraint UK_q6jibbenp7o9v6tq178xg88hg unique (user_id);
alter table verification_token add constraint UK_p678btf3r9yu6u8aevyb4ff0m unique (token);
alter table authority add constraint FKkjkd05i1g2bewgkh7u4yh606x foreign key (user_id) references renovation_user (id);
alter table forgotten_password_token add constraint FKogk6u6byc7biax27llb98ebme foreign key (user_id) references renovation_user (id);
alter table renovation add constraint FKayhwx6uv9ku1rohaog4phuloj foreign key (user_id) references renovation_user (id);
alter table room add constraint FK4bct9mv40d3hbre7ccqdcqy1q foreign key (renovation_id) references renovation (id);
alter table tag add constraint FK1q79k4wif1at9kcpsvrnja70d foreign key (renovation) references renovation (id);
alter table task add constraint FK82rswqeoy31roi3ay3p9ksha6 foreign key (renovation_id) references renovation (id);
alter table task_room add constraint FKfv55x16kojpuwygprobd0wpak foreign key (room_id) references room (id);
alter table task_room add constraint FK5ry8x17wkej43edtjl5drueav foreign key (task_id) references task (id);
alter table verification_token add constraint FKltvrqq324ejfqicl9qk7hylc0 foreign key (user_id) references renovation_user (id);
