package nz.ac.canterbury.seng302.homehelper.unit.service;

import nz.ac.canterbury.seng302.homehelper.service.ProfanityService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

@ExtendWith(MockitoExtension.class)
public class ProfanityServiceTest {
    private ProfanityService profanityService;

    @BeforeEach
    public void setup() {
        profanityService = new ProfanityService();
        profanityService.init();
    }

    // Value source strings generated by ChatGPT
    @ParameterizedTest
    @ValueSource(strings = {
            "My Fucking House",
            "This is Bullshit",
            "Damn That’s Crazy",
            "What a Bitch Move",
            "F*ck This Place",
            "Shit Happens",
            "You Asshole",
            "Go to Hell",
            "Goddamn Garage",
            "Fucking Legend",
            "Piece of Sh*t",
            "Damn Garden Shed",
            "Asshat Central",
            "Hellhole Apartment",
            "WTF Backyard",
            "FML Kitchen",
            "Crappy Little Flat",
            "Bloody Mess Room",
            "Dickhead’s Car",
            "Shut the F*ck Up",
            "Damn It All",
            "Fucking Nonsense",
            "Holy Shit Show",
            "You Stupid Bastard",
            "Asswipe Territory",
            "Total Dick Move",
            "Crap Shack",
            "Bitchin’ Ride",
            "F*ckin’ Treehouse"
    })
    void testCheckProfanityLocal_WhenBadWord_ThenReturnTrue(String message) {
        assertTrue(profanityService.checkProfanityLocal(message));
    }

    // Value source strings generated by ChatGPT
    @ParameterizedTest
    @ValueSource(strings = {
            "Assignment",
            "My Lovely House",
            "Peaceful Garden",
            "Charming Apartment",
            "Sunny Backyard",
            "The Cozy Den",
            "Little Green Shed",
            "Happy Camper Van",
            "Quiet Retreat",
            "Elegant Flat",
            "Friendly Workspace",
            "Warm Fireplace",
            "Reading Place",
            "Playful Kittens",
            "Cool Breeze Balcony",
            "Starry Night Cabin",
            "Weekend Hideaway",
            "Minimalist Studio",
            "Colorful Corner",
            "Open Sky Deck",
            "Modern Kitchen",
            "Wholesome Home",
            "Gentle Breeze",
            "Tranquil Space",
            "Bright Sunroom",
            "Greenhouse Oasis",
            "Vintage Loft",
            "Family Room",
            "Golden Hour Porch",
            "Cozy Bunkhouse",
            "Tidy Workspace"
    })
    void testCheckProfanityLocal_WhenClean_ThenReturnFalse(String message) {
        assertFalse(profanityService.checkProfanityLocal(message));
    }
}
